description: efficient net
runner: r001
device: cuda
batch_size: 8
max_epoch: 30
fobj: ce
model:
    model_type: efficientnetb7
    pretrained: true
optimizer: 
    optim_type: adam
    lr: 0.0003
scheduler:
    scheduler_type: pass
sampler:
    sampler_type: random
split: 
    split_type: cskf
    split_num: 5
