description: efficient net b2 baseline
runner: r001
device: cuda
batch_size: 32
max_epoch: 30
fobj: ce
model:
    model_type: efficientnetb2
    pretrained: true
optimizer: 
    optim_type: rmsprop
    lr: 0.0003
scheduler:
    scheduler_type: cosine
sampler:
    sampler_type: random
split: 
    split_type: cskf
    split_num: 5
