description: scaled small lr
runner: r004
device: cuda
batch_size: 64
max_epoch: 40
fobj: ce
dlt_bias: false
dlt_var: false
model:
    model_type: efficientnetb2_metric
    pretrained: true
optimizer: 
    optim_type: adam
    lr: 0.0001
scheduler:
    scheduler_type: cosine
sampler:
    sampler_type: random
split: 
    split_type: cskf
    split_num: 5
augment:
    - horizontalflip
    - randomrotate90
