d_expescription: whole data 
runner: r004
device: cuda
batch_size: 24
max_epoch: 20
fobj: sce
dlt_bias: false
dlt_var: false
model:
    model_type: efficientnetb5_metric
    pretrained: true
optimizer: 
    optim_type: adam
    lr: 0.0001
scheduler:
    scheduler_type: cosine
sampler:
    sampler_type: random
split: 
    split_type: wds
    split_num: 5
augment:
    - horizontalflip
    - randomrotate90
    - mixup
    - normalize_plate_exp
ttas:
    - original
    - rotate90
    - rotate180
    - rotate270
    - flip
    - fliprotate90
    - fliprotate180
    - fliprotate270
